jobs:
- name: subway
  public: true
  plan:
  - get: cf-subway
    trigger: true
  - task: run-tests
    file: cf-subway/build.yml

- name: pilot
  serial: true
  public: true
  plan:
  - get: cf-subway
    trigger: true
    passed: [subway]
  - get: haash-broker
  - task: build-backend-broker
    file: cf-subway/scripts/build-backend-broker.yml

resources:
- name: cf-subway
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/cf-subway.git
    branch: master

- name: haash-broker
  type: git
  source:
    uri: https://github.com/drnic/haash-broker.git
    branch: parameters
