jobs:
- name: subway
  public: true
  plan:
  - get: cf-subway
    trigger: true
  - task: run-tests
    file: cf-subway/build.yml

- name: pilot
  serial: true
  public: true
  plan:
  - get: cf-subway
    trigger: true
    passed: [subway]

- name: backends
  serial: true
  public: true
  plan:
  - get: cf-subway
    trigger: true
  - task: deploy-test-backend
    file: cf-subway/scripts/deploy-test-backend.yml
    config:
      params:
        BOSH_TARGET: {{bosh-target}}
        BOSH_USERNAME: {{bosh-username}}
        BOSH_PASSWORD: {{bosh-password}}

resources:
- name: cf-subway
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/cf-subway.git
    branch: master
